name: "Helm Chart Lint"
on: [pull_request, push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Helm
        uses: azure/setup-helm@v3
      - name: Lint Charts
        run: |
          for chart in applications/charts/*; do
            helm lint "$chart"
          done
      - name: Template-Check Charts
        run: |
          for chart in applications/charts/*; do
            helm template "$chart" --debug
          done