name: "OPA Policy Scan"
on: [pull_request]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Conftest
        run: |
          curl -L https://github.com/open-policy-agent/conftest/releases/download/v0.32.0/conftest_0.32.0_Linux_x86_64.tar.gz | tar xz -C /usr/local/bin conftest
      - name: Run OPA scans
        run: |
          conftest test gitops/clusters/base --policy policies/